/**
 * Webpack 5 base configuration shared by main, renderer, and webui builds.
 *
 * Replaces the configuration that was previously generated by
 * `electron-webpack` v2.8.2. The crypto monkey-patch is no longer needed
 * because Webpack 5 uses a modern hash function by default.
 */

const path = require('path');
const TerserPlugin = require('terser-webpack-plugin');
const appPkg = require('./package.json');

const electronVersion = appPkg.devDependencies?.electron || appPkg.dependencies?.electron || '40';
const electronMajor = parseInt(electronVersion.replace(/[^\d]/g, ''), 10) || 40;

// All production dependencies from package.json are externals in electron builds.
// The whiteListedModules are bundled instead of treated as externals.
const whiteListedModules = [
  'stream-json-rpc',
  'electron-better-web-request',
  'shared-redux',
  'uuid',
  'is-equal-shallow',
  'rxjs',
  'tslib',
];

function getExternals(additionalWhitelist = []) {
  const whitelist = new Set([...whiteListedModules, ...additionalWhitelist]);
  const deps = Object.keys(appPkg.dependencies || {});
  return deps.filter(d => !whitelist.has(d));
}

function getBaseConfig(env, argv) {
  const isProd = argv.mode === 'production';
  const isDev = !isProd;

  return {
    context: path.resolve(__dirname),

    devtool: isProd ? (process.env.WEBPACK_DEVTOOL || 'source-map') : 'eval-source-map',

    resolve: {
      alias: {
        '@': path.resolve(__dirname, 'src'),
        common: path.resolve(__dirname, 'src/common'),
        '@electron/internal/renderer/ipc-renderer-internal':
          path.resolve(__dirname, 'app/lib/ipc-renderer-internal.ts'),
        'uuid/v4$': path.resolve(__dirname, 'src/lib/uuid-v4.js'),
        // Deduplicate graphql — @getstation/reactive-graphql bundles its own copy
        'graphql': path.resolve(__dirname, '../../node_modules/graphql'),
      },
      extensions: ['.js', '.ts', '.tsx', '.json', '.node'],
    },

    module: {
      rules: [
        {
          test: /\.tsx?$/,
          exclude: /node_modules/,
          use: [
            {
              loader: 'ts-loader',
              options: {
                transpileOnly: true,
                configFile: path.resolve(__dirname, 'tsconfig.json'),
              },
            },
          ],
        },
        {
          test: /\.jsx?$/,
          use: [
            {
              loader: 'babel-loader',
              options: {
                configFile: false,
                babelrc: false,
                presets: [
                  ['@babel/preset-env', { targets: { electron: String(electronMajor) } }],
                  '@babel/preset-react',
                  ['@babel/preset-typescript', { isTSX: true, allExtensions: true }],
                ],
                plugins: [
                  ['@babel/plugin-proposal-decorators', { legacy: true }],
                  ['@babel/plugin-proposal-class-properties', { loose: true }],
                  '@babel/plugin-transform-runtime',
                  ['@babel/plugin-transform-private-methods', { loose: true }],
                ],
              },
            },
          ],
        },
        {
          test: /\.graphql$/,
          exclude: /node_modules/,
          type: 'asset/source',
        },
        {
          test: /\.mjs$/,
          include: /node_modules/,
          type: 'javascript/auto',
        },
        {
          test: /\.(woff2?|eot|ttf|otf)(\?.*)?$/,
          type: 'asset/resource',
          generator: { filename: 'fonts/[name]--[folder][ext]' },
        },
        {
          test: /\.(png|jpe?g|gif|svg)(\?.*)?$/,
          type: 'asset/resource',
          generator: { filename: 'imgs/[name]--[folder][ext]' },
          parser: { dataUrlCondition: { maxSize: 10240 } },
        },
        {
          test: /\.(mp4|webm|ogg|mp3|wav|flac|aac)(\?.*)?$/,
          type: 'asset/resource',
          generator: { filename: 'media/[name]--[folder][ext]' },
          parser: { dataUrlCondition: { maxSize: 10240 } },
        },
        {
          test: /\.node$/,
          loader: 'node-loader',
        },
      ],
    },

    optimization: {
      minimizer: isProd
        ? [
            new TerserPlugin({
              terserOptions: {
                compress: { passes: 2 },
                // Services registry keys rely on constructor names at runtime.
                // Minifying class/function names can cause collisions like
                // "browser-window:A".
                keep_classnames: true,
                keep_fnames: true,
              },
              parallel: true,
            }),
          ]
        : [],
    },

    stats: 'errors-only',
  };
}

module.exports = { getBaseConfig, getExternals, electronMajor };