/**
 * Build config for electron main process
 */
const { resolve } = require('path');
const webpack = require('webpack');
const { RawSource } = require('webpack-sources');
const { mutateWebpackConfig } = require('./webpack.config.common');

const preloadEntrypoints = new Set([
  'preload.js',
  'main-preload.js',
  'cli-preload.js',
  'worker-preload.js',
]);
const sourceMapSupportBannerPattern = /require\("source-map-support\/source-map-support\.js"\)\.install\(\)[;,]/;

class StripSourceMapSupportFromPreloadsPlugin {
  apply(compiler) {
    compiler.hooks.emit.tap('StripSourceMapSupportFromPreloadsPlugin', (compilation) => {
      for (const filename of preloadEntrypoints) {
        const asset = compilation.assets[filename];
        if (!asset) continue;

        const source = asset.source().toString();
        if (!sourceMapSupportBannerPattern.test(source)) continue;

        compilation.assets[filename] = new RawSource(source.replace(sourceMapSupportBannerPattern, ''));
      }
    });
  }
}

/**
 * @param config {webpack.Configuration}
 */
module.exports = (config) => {
  // console.log(require('util').inspect(config, { depth: 8 }));
  mutateWebpackConfig(config);

  if (config.mode === 'development') {
    // webui is generated by another webpack process, this is the glue
    config.plugins.push(new webpack.DefinePlugin({
      __webpack_public_path__: JSON.stringify(resolve(config.output.path, '../renderer')),
      __webpack_main_path__: JSON.stringify(config.output.path)
    }));

    config.devtool = 'source-map';
  }

  config.target = 'electron-main';
  config.plugins.push(new StripSourceMapSupportFromPreloadsPlugin());

  return config;
};
